### ISSUE TITLE
Incorrect import of font-roboto and incorrect font-family name

### ISSUE THREAD

**Issue by plequang** [GoogleWebComponents/google-signin#51]
Hi,

The link element to import the font-roboto component in google-signin.html is incorrect :

``` html
<link rel="import" href="../components/font-roboto/roboto.html">
```

should be 

``` html
<link rel="import" href="../font-roboto/roboto.html">
```

This is annoying because vulcanize is failing to load this file.

Also, font-roboto componenent is using RobotoDraft font, so the syle definition is also incorrect.

Instead of 

``` css
.buttonText {
                ...
                font-family: 'Roboto',arial,sans-serif;
            }
```

it should be  :

``` css
.buttonText {
                ...
                font-family: 'RobotoDraft',arial,sans-serif;
            }
```

And finally, I think we can use font-roboto#0.4.0 instead of font-roboto#master : the content is the same, and it  will remove bower components resolution (for example, paper-elements#0.4.0 depends on font-roboto#0.4.0).

A pull request is in progress, but let me know if some of the suggested changes looks not correct.
